create table exp_categories (
  category_id    number generated by default as identity primary key,
  name  varchar2(100) not null unique
);



create table employee (
  emp_id            number generated by default as identity primary key,
  emp_no   varchar2(20) unique,
  full_name     varchar2(150) not null,
  email         varchar2(150) not null unique,
  department    varchar2(100),
  manager_id    number references employee(emp_id),
  app_username  varchar2(100) unique
);


create table emp_expenses (
  expense_id            number generated by default as identity primary key,
  emp_id   number not null references employee(emp_id),
  category_id   number not null references exp_categories(category_id),
  description   varchar2(200) not null,
  amount        number(10,2) not null,
  spent_on      date default sysdate,
  status        varchar2(20) default 'PENDING' check (status in ('PENDING','APPROVED','REJECTED')),
  receipt_blob  blob,
  receipt_name  varchar2(255),
  receipt_mime  varchar2(100),
  created_by    varchar2(100) ,
  created_on    date default sysdate,
  approved_by   varchar2(100),
  approved_on   date,
  reject_reason varchar2(4000)
);




insert into exp_categories (name) values ('Food');
insert into exp_categories (name) values ('Travel');
insert into exp_categories (name) values ('Rent');
insert into exp_categories (name) values ('Software');
insert into exp_categories (name) values ('Utility bills');
insert into exp_categories (name) values ('Other');

select * from exp_categories;

insert into employee (emp_no, full_name, email, department, manager_id, app_username)
values ('EMP001', 'Sarah Patel', 'sarah.patel@gmail.com', 'Finance', null, 'SARAH_P');

insert into employee (emp_no, full_name, email, department, manager_id, app_username)
values ('EMP002', 'David paul', 'david.paul@gmail.com', 'Engineering', null, 'DAVID_P');

insert into employee (emp_no, full_name, email, department, manager_id, app_username)
select 'EMP003', 'Priya Nair', 'priya.nair@gmail.com', 'Finance', emp_id, 'PRIYA_N'
from employee where emp_no = 'EMP001';

insert into employee (emp_no, full_name, email, department, manager_id, app_username)
select 'EMP004', 'James Kass', 'james.kass@gmail.com', 'Finance', emp_id, 'JAMES_K'
from employee where emp_no = 'EMP001';

insert into employee (emp_no, full_name, email, department, manager_id, app_username)
select 'EMP005', 'Emily Robert', 'emily.rober@gmail.com', 'Engineering', emp_id, 'EMILY_R'
from employee where emp_no = 'EMP002';

insert into employee (emp_no, full_name, email, department, manager_id, app_username)
select 'EMP006', 'Michael Twing', 'michael.twing@gmail.com', 'Engineering', emp_id, 'MICHAEL_T'
from employee where emp_no = 'EMP002';


select * from employee;

insert into emp_expenses (emp_id, category_id, description, amount, spent_on, status)
select e.emp_id, c.category_id, v.description, v.amount, v.spent_on, v.status
from (
  select 'PRIYA_N' emp, 'Food' cat, 'Team lunch'              description, 46.20  amount, date '2026-07-12' spent_on, 'APPROVED' status from dual union all
  select 'PRIYA_N', 'Travel', 'Train tickets',                   38.00, date '2026-07-08', 'APPROVED' from dual union all
  select 'PRIYA_N', 'Software', 'Design tool license',           29.00, date '2026-09-01', 'PENDING'  from dual union all

  select 'JAMES_K', 'Rent', 'Coworking desk - July',            250.00, date '2026-07-01', 'APPROVED' from dual union all
  select 'JAMES_K', 'Utility bills', 'Internet bill',            60.00, date '2026-07-18', 'APPROVED' from dual union all
  select 'JAMES_K', 'Other', 'Office supplies',                  23.60, date '2026-08-22', 'REJECTED' from dual union all

  select 'EMILY_R', 'Travel', 'Flight to conference',           320.00, date '2026-08-22', 'APPROVED' from dual union all
  select 'EMILY_R', 'Travel', 'Hotel (2 nights)',                240.00, date '2026-09-10', 'PENDING'  from dual union all
  select 'EMILY_R', 'Food', 'Client dinner',                      61.00, date '2026-09-06', 'PENDING'  from dual union all

  select 'MICHAEL_T', 'Software', 'Cloud storage plan',           9.99, date '2026-08-01', 'APPROVED' from dual union all
  select 'MICHAEL_T', 'Software', 'Code editor subscription',    15.00, date '2026-09-01', 'PENDING'  from dual union all
  select 'MICHAEL_T', 'Utility bills', 'Electricity bill',       85.10, date '2026-08-15', 'APPROVED' from dual
) v,
 employee e, 
 exp_categories c
 where  c.name = v.cat and e.app_username = v.emp;

select * from emp_expenses;

commit;