-- =====================================================================
-- Employee Expense Tracker — Database Scripts
-- Oracle APEX
--
-- Run sections in order:
--   1. Tables
--   2. Reporting View
--   3. Reference Data (categories)
--   4. Sample Data (employees, expenses)
-- =====================================================================


-- =====================================================================
-- 1. TABLES
-- =====================================================================

create table exp_categories (
  category_id  number generated by default as identity primary key,
  name         varchar2(100) not null unique
);

create table employee (
  emp_id        number generated by default as identity primary key,
  emp_no        varchar2(20) unique,
  full_name     varchar2(150) not null,
  email         varchar2(150) not null unique,
  department    varchar2(100),
  manager_id    number references employee(emp_id),
  app_username  varchar2(100) unique
);

create table emp_expenses (
  expense_id     number generated by default as identity primary key,
  emp_id         number not null references employee(emp_id),
  category_id    number not null references exp_categories(category_id),
  description    varchar2(200) not null,
  amount         number(10,2) not null,
  spent_on       date default sysdate,
  status         varchar2(20) default 'PENDING' check (status in ('PENDING', 'APPROVED', 'REJECTED')),
  receipt_blob   blob,
  receipt_name   varchar2(255),
  receipt_mime   varchar2(100),
  created_by     varchar2(100),
  created_on     date default sysdate,
  approved_by    varchar2(100),
  approved_on    date,
  reject_reason  varchar2(4000)
);


-- =====================================================================
-- 2. REPORTING VIEW
-- Backs the Expense Explorer (Faceted Search) page and other
-- reporting-style queries, so results show readable names instead
-- of raw IDs.
-- =====================================================================

create or replace view emp_expenses_v as
select ee.expense_id,
       ee.description,
       ee.amount,
       ee.spent_on,
       ee.status,
       c.name as category_name,
       emp.full_name as employee_name,
       ee.receipt_name
from emp_expenses ee,
 exp_categories c , 
 employee emp 
where emp.emp_id = ee.emp_id
and c.category_id = ee.category_id;


-- =====================================================================
-- 3. REFERENCE DATA — Expense Categories
-- =====================================================================

insert into exp_categories (name) values ('Food');
insert into exp_categories (name) values ('Travel');
insert into exp_categories (name) values ('Rent');
insert into exp_categories (name) values ('Software');
insert into exp_categories (name) values ('Utility bills');
insert into exp_categories (name) values ('Other');

commit;


-- =====================================================================
-- 4. SAMPLE DATA — Employees
-- Managers first (manager_id left null), then their direct reports.
-- =====================================================================

insert into employee (emp_no, full_name, email, department, manager_id, app_username)
values ('EMP001', 'Sarah Patel', 'sarah.patel@gmail.com', 'Finance', null, 'SARAH_P');

insert into employee (emp_no, full_name, email, department, manager_id, app_username)
values ('EMP002', 'David Paul', 'david.paul@gmail.com', 'Engineering', null, 'DAVID_P');

insert into employee (emp_no, full_name, email, department, manager_id, app_username)
select 'EMP003', 'Priya Nair', 'priya.nair@gmail.com', 'Finance', emp_id, 'PRIYA_N'
from employee where emp_no = 'EMP001';

insert into employee (emp_no, full_name, email, department, manager_id, app_username)
select 'EMP004', 'James Kass', 'james.kass@gmail.com', 'Finance', emp_id, 'JAMES_K'
from employee where emp_no = 'EMP001';

insert into employee (emp_no, full_name, email, department, manager_id, app_username)
select 'EMP005', 'Emily Robert', 'emily.rober@gmail.com', 'Engineering', emp_id, 'EMILY_R'
from employee where emp_no = 'EMP002';

insert into employee (emp_no, full_name, email, department, manager_id, app_username)
select 'EMP006', 'Michael Twing', 'michael.twing@gmail.com', 'Engineering', emp_id, 'MICHAEL_T'
from employee where emp_no = 'EMP002';

commit;


-- =====================================================================
-- 4a. SAMPLE DATA — Expenses
-- =====================================================================

insert into emp_expenses (emp_id, category_id, description, amount, spent_on, status)
select e.emp_id, c.category_id, v.description, v.amount, v.spent_on, v.status
from (
  select 'PRIYA_N'    as emp, 'Food'          as cat, 'Team lunch'                 as description,  46.20 as amount, date '2026-07-12' as spent_on, 'APPROVED' as status from dual union all
  select 'PRIYA_N',          'Travel',             'Train tickets',                            38.00,          date '2026-07-08',          'APPROVED' from dual union all
  select 'PRIYA_N',          'Software',           'Design tool license',                      29.00,          date '2026-09-01',          'PENDING'  from dual union all

  select 'JAMES_K',          'Rent',               'Coworking desk - July',                   250.00,          date '2026-07-01',          'APPROVED' from dual union all
  select 'JAMES_K',          'Utility bills',      'Internet bill',                             60.00,          date '2026-07-18',          'APPROVED' from dual union all
  select 'JAMES_K',          'Other',              'Office supplies',                           23.60,          date '2026-08-22',          'REJECTED' from dual union all

  select 'EMILY_R',          'Travel',             'Flight to conference',                     320.00,          date '2026-08-22',          'APPROVED' from dual union all
  select 'EMILY_R',          'Travel',             'Hotel (2 nights)',                         240.00,          date '2026-09-10',          'PENDING'  from dual union all
  select 'EMILY_R',          'Food',               'Client dinner',                             61.00,          date '2026-09-06',          'PENDING'  from dual union all

  select 'MICHAEL_T',        'Software',           'Cloud storage plan',                         9.99,          date '2026-08-01',          'APPROVED' from dual union all
  select 'MICHAEL_T',        'Software',           'Code editor subscription',                  15.00,          date '2026-09-01',          'PENDING'  from dual union all
  select 'MICHAEL_T',        'Utility bills',      'Electricity bill',                          85.10,          date '2026-08-15',          'APPROVED' from dual
) v
, employee      e  
, exp_categories c  ;
WHERE e.app_username = v.emp
 AND c.name        = v.cat;
 
commit;


-- =====================================================================
-- 5. VERIFY
-- =====================================================================

select * from exp_categories;
select * from employee;
select * from emp_expenses;
select * from emp_expenses_v;
